name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker-compose build

    - name: Push Docker Image to Docker Hub
      run: docker tag cidade-limpa:latest ${{ secrets.DOCKER_HUB_USERNAME }}/cidade-limpa:${{ github.sha }}
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cidade-limpa:${{ github.sha }}

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service (Staging)
      uses: azure/webapps-deploy@v2
      with:
        app-name: "cidade-limpa-staging"
        images: "${{ secrets.DOCKER_HUB_USERNAME }}/cidade-limpa:${{ github.sha }}"

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service (Production)
      uses: azure/webapps-deploy@v2
      with:
        app-name: "cidade-limpa-production"
        images: "${{ secrets.DOCKER_HUB_USERNAME }}/cidade-limpa:${{ github.sha }}"
